// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDKXPxO2ukvgp42s8IPyWbNYWKI4peSTa8',
    appId: '1:351611009444:web:84fdfd3bb70c04b3356931',
    messagingSenderId: '351611009444',
    projectId: 'swiftlead-44444',
    authDomain: 'swiftlead-44444.firebaseapp.com',
    storageBucket: 'swiftlead-44444.appspot.com',
    measurementId: 'G-B14KLBJVJB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAufWXdlLew9YhuWVZvm3J3kVWrWvdNUuE',
    appId: '1:351611009444:android:3d53cd95bb957a7c356931',
    messagingSenderId: '351611009444',
    projectId: 'swiftlead-44444',
    storageBucket: 'swiftlead-44444.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAkTlsLWgi7MkVsyqMjkAFOZQwQYb1AuTI',
    appId: '1:351611009444:ios:bb13b760b3c80cdc356931',
    messagingSenderId: '351611009444',
    projectId: 'swiftlead-44444',
    storageBucket: 'swiftlead-44444.appspot.com',
    iosBundleId: 'com.example.swiftlead',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAkTlsLWgi7MkVsyqMjkAFOZQwQYb1AuTI',
    appId: '1:351611009444:ios:2e899426e3e43fb2356931',
    messagingSenderId: '351611009444',
    projectId: 'swiftlead-44444',
    storageBucket: 'swiftlead-44444.appspot.com',
    iosBundleId: 'com.example.swiftlead.RunnerTests',
  );
}
